---
dist: trusty
language: python
python: "2.7"
before_install:
 - ln -s ansible-win-applocker ../juju4.win-applocker
install:
  - sudo apt-get install libxml2-utils
  - pip install ansible ansible-lint
  - ansible --version
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "echo \"[test-kitchen]\nlocalhost\" > inventory"

  - "ansible-lint tasks/main.yml"

# Check the role/playbook's syntax.
  - "ansible-playbook -i inventory --syntax-check test/integration/default/default.yml"

# Applocker templates
  - "for f in templates/applocker-*.xml.j2; do echo \"== $f\"; xmllint $f > /dev/null; done"
