---

- name: Ensure ansible directories exist
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ win_temp_dir }}"
    - "{{ win_log_dir }}"

- name: Restrict permissions for ansible directories
  ansible.windows.win_acl:
    path: "{{ item.p }}"
    user: "{{ item.u }}"
    rights: "{{ item.r }}"
    type: "{{ item.t }}"
    state: "{{ item.s }}"
    inherit: "{{ item.i }}"
    propagation: "{{ item.pr }}"
  with_items:
    - { p: "{{ win_temp_dir }}",
        u: 'BUILTIN\Users',
        r: 'ReadAndExecute,Write',
        t: allow,
        s: absent,
        i: 'ContainerInherit, ObjectInherit',
        pr: 'None'
    }
    - { p: "{{ win_log_dir }}",
        u: 'BUILTIN\Users',
        r: 'ReadAndExecute,Write',
        t: allow,
        s: absent,
        i: 'ContainerInherit, ObjectInherit',
        pr: 'None'
    }

- name: Include windows-whitelist
  ansible.builtin.include_tasks: windows-whitelist.yml
  when: win_applocker_enable|bool

- name: Include testing-applocker
  ansible.builtin.include_tasks: testing-applocker.yml
  when: win_testing_applocker|bool
