---

- name: Testing | AppLocker via powershell Get-AppLockerPolicy
  win_shell: "Get-AppLockerPolicy -Effective | Test-AppLockerPolicy -Path {{ item }}"
  with_items: "{{ win_testing_applocker_filepath | default([]) }}"
  register: testal_results
- name: Debug | testal_results
  ansible.builtin.debug: var=testal_results

- name: Ensure sysinternals tools are present with chocolatey
  win_chocolatey:
    name: sysinternals
    state: present

- name: Check directories permissions for world-writeable paths
  win_shell: "C:\\ProgramData\\chocolatey\\lib\\sysinternals\\tools\\accesschk.exe -w Users \"{{ item }}\""
  with_items: "{{ win_testing_applocker_dirpath | default([]) }}"
  register: wpath_results
  ignore_errors: true
- name: Debug | wpath_results
  ansible.builtin.debug: var=wpath_results

- name: Remove user _test
  win_user:
    name: _test
    state: absent
## FIXME! failing on second pass, https://groups.google.com/forum/#!topic/ansible-project/_ydkYXZibrM
##  https://technet.microsoft.com/en-us/library/cc732593(v=ws.10).aspx
- name: Ensure user _test is present
  win_user:
    name: _test
    password: "{{ ansible_become_password }}"
    state: present
    groups:
      - Users

## https://github.com/3gstudent/Bypass-Windows-AppLocker
- name: upload test script
  win_template:
    src: AppLockerBypassChecker-v1.ps1
    dest: "{{ win_temp_dir }}\\AppLockerBypassChecker-v1.ps1"

## FIXME! ProgramData dir is user writeable! opscode\inspec
- block:
    - name: AppLockerBypassChecker-v1 for user?
      win_shell: "Powershell -Exec Bypass -File \"{{ win_temp_dir }}\\AppLockerBypassChecker-v1.ps1\" \"{{ item }}\""
      become: yes
      become_user: _test
      with_items: "{{ win_testing_applocker_dirpath | default([]) }}"
      register: bypass_results
    - name: Debug | bypass_results
      ansible.builtin.debug: var=bypass_results
  when: win_testing_applocker_bypasschecker

# https://oddvar.moe/2018/01/14/putting-data-in-alternate-data-streams-and-how-to-execute-it/
# - name: install teamviewer for some testing
#   win_chocolatey: name=teamviewer state=present upgrade=no
# FIXME! out-file: The given's path format is not supported
# - name: try to push bginfo in teamviewer logfile alternate data stream
#   win_shell: >
#     type c:\\ProgramData\\chocolatey\\bin\\bginfo.exe
#       > "C:\\program files (x86)\\Teamviewer\\TeamViewer13_Logfile.log:bginfo.exe"
# - name: try to execute
#   win_shell: >
#     wmic process call create '"C:\\program files (x86)\\Teamviewer\\TeamViewer13_Logfile.log:bginfo.exe"'

# https://github.com/strictlymike/Invoke-SchmappLocker/blob/master/Invoke-SchmappLocker.ps1
# https://blog.didierstevens.com/2011/01/25/circumventing-srp-and-applocker-to-create-a-new-process-by-design/


- name: Check log for blocked apps
  win_shell: Get-WinEvent -LogName 'Microsoft-Windows-AppLocker/EXE and DLL' | Where { $_.ID -eq 8004 }
  register: winevt
  ignore_errors: true
  changed_when: false
- name: Debug | winevt output
  ansible.builtin.debug: var=winevt.stdout_lines
